### ISSUE TITLE
Can‘t find data

### ISSUE THREAD

**Issue by spawner9** [zabaras/inn-surrogate#1]
Excuse me， your code file ‘load_data.py’ will load a train data file 'Config_2_train_obs_1pc.hdf5'， but will it is？ I can’t also find your 2-D data in the paper

**Comment by Govinda7** [comment]
Hi,

You can find the Config_2_train_obs_1pc.hdf5 and other 2D data here: https://zenodo.org/record/4631233#.YZZrnNbMLt1

This link is already provided in the readme file as well. 

Thanks,
Govinda.

**Comment by spawner9** [comment]
Thanks very much，I just carefully examined the 2D file，and finally got the data website in the readme.py。



发自我的iPhone


------------------ Original ------------------
From: Govinda ***@***.***&gt;
Date: Thu,Nov 18,2021 11:09 PM
To: zabaras/inn-surrogate ***@***.***&gt;
Cc: spawner9 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [zabaras/inn-surrogate] Can‘t find data (Issue #1)





 
Hi,
 
You can find the Config_2_train_obs_1pc.hdf5 and other 2D data here: https://zenodo.org/record/4631233#.YZZrnNbMLt1
 
This link is already provided in the readme file as well.
 
Thanks,
 Govinda.
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
